[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"

[[session]]
name = "Code ğŸ’»"
path = "~/main"
startup_command = "l"

[[session]]
name = "tmux config"
path = "~/main/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "neovim config"
path = "~/main/dotfiles/.config/nvim"

[[session]]
name = "home config"
path = "~/main/dotfiles/"

[[session]]
name = "sesh config"
path = "~/main/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Thesis ï†œ "
path = "~/main/projects/thesis/"
startup_command = "yazi"
